blog/urls.py
from django.urls import include, path
from . import views 

from django.conf import settings
from django.conf.urls.static import static
# urlpatterns = [
    # path('index/',views.index, name='main-view')
# ]
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('authors/', views.author_list, name ='author_list'),
    path('books/', views.books_list, name = 'books_list'),
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login,name='login')
    ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls','blog'),namespace='blog')), 
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Books(models.Model):
    author = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    language = models.CharField(max_length=50)
    genre = models.CharField(max_length=50)
    link = models.URLField(max_length = 200)
    description = models.TextField()
    rating = models.FloatField()

    def __str__(self):
        return f'{self.author} {self.name}'



GENDER_OPTIONS = (
    ('M', 'Man'),
    ('W', 'Woman')
)
class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    # email = models.EmailField()
    address = models.TextField(blank = True ,null=True)
    telephone = models.CharField(max_length=30,blank=True, null=True)
    birth_year = models.DateField(blank=True, null= True)
    gender = models.CharField(max_length=1, choices = GENDER_OPTIONS,blank=True, null=True)
    avatar = models.ImageField(upload_to ='avatars',blank = True, null=True)


    def __str__(self):
        return f'{self.first_name} {self.last_name}'



class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateField(default=timezone.now)
    published_date = models.DateField(blank=True,null=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.contrib.auth.models import User
 

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите свой email', }), label='')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль', }), label='')
    # (label='Введите свой email')

    def clean(self):
        self.cleaned_data.get('username')
        self.cleaned_data.get('password')
        return self.cleaned_data

class RegistrationForm(forms.ModelForm):
    email =forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите свой email', }), label='')
    password1=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль', }), label='')
    password2=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль повторно', }), label='')
    class Meta:
        model = User 
        fields = ('email',)

    def clean_password2(self):
        cd = self.cleaned_data 
        if cd ['password1'] != ['password2']:
            raise forms.ValidationError('Ваши пароли не совпали')
        return cd['password2']

blog/views.py
from django.shortcuts import render,HttpResponseRedirect
from .models import Post,Author,Books
from.forms import LoginForm,RegistrationForm
from django.contrib.auth import authenticate,login
from django.contrib import messages
from django.contrib.auth.models import User
# Create your views here.
# def index(request):
#     posts = Post.objects.all()
#     return render(request, 'index.html',{"posts":posts})
def user_login(request):
    if request.method == 'GET':
        form = LoginForm()
        
    else:
        print(request.POST)
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect('/')
                else: 
                    messages.error(request, 'Ваш аккаунт заблокирован')
            else:
                messages.error(request, 'неправильный ввод данных')

    return render(request,'blog/login.html',{'login_form': form})

def user_register(request):
    if request.method =='GET':
        form = RegistrationForm()
    else:
        form = RegistrationForm(request.POST)
        # cd = form.cleaned_data 
        user_exists = User.objects.filter(email= request.POST['email']).exists()
        if not user_exists:
            if form.is_valid():
                new_user = form.save(commit = False)
                new_user.username = request.POST['email']
                Author.objects.create(user=new_user, first_name='',last_name='')
                return HttpResponseRedirect('/login/')
            else:
                messages.error(request,'неправильные данные')

        else:
            massages.error(request,'Такой пользователь есть')

    return render(request,'blog/register.html',{'register_form':form})


def post_list(request):
    posts = Post.objects.filter(author__id =2)
    return render(request, 'blog/post_list.html',{"posts":posts})

def author_list(request):
    authors = Author.objects.all()
    return render(request, 'blog/author_list.html',{"authors":authors})

def books_list(request):
    books = Books.objects.all()
    return render(request,'blog/books_list.html',{"books":books})

blog/templates/blog/author_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <body>
{% include 'blog/header.html' %}    
        <div class="container">
            {% for author in authors %}
                <div class="col-md-3">
                    {% if author.avatar %}
                    <img class="avatar-img" src="{{author.avatar.url}}">
                        {% else %}
                    <img class="avatar-img" src="{% static 'img/foto.png' %}">
                    {% endif %}
                    
                    <h2>{{author.first_name}} {{author.last_name}}</h2>
                    <h5>{{author.email}}</h5>
                    <h5>{{author.birth_year}}</h5>
                    <h5>{{author.telephone}}</h5>

                </div>
            {% endfor %}

        </div>
    </body>
    {% endblock %}

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>Django Men's blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    {% block content %}

    {% endblock %}
    </html>

blog/templates/blog/books_list.html
{% extends 'blog/base.html' %}
{% load static %}
   
{% block content %}
    <body>
{% include 'blog/header.html' %}  
        <div class="container">
            {% for book in books %}
                <div class="col-md-4">
                    <h2>{{book.author}} </h2>
                    <h5>{{book.name}}</h5>
                    <h5>{{book.genre}}</h5>
                    <h5>{{book.language}}</h5>

                </div>
            {% endfor %}

        </div>
    </body>
    {% endblock %}

blog/templates/blog/header.html
{% load static %}
<div class="page-header">
    <h1><a href="/">Django Men's Blog</a></h1>
    <ul id="header-links">
        <li><a href="{% url 'blog:post_list' %}">Home</a></li>
        <li><a href="/authors">Authors</a></li>
        <li><a href="{% url 'blog:books_list' %}">Books</li>
    </ul>
</div>

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}"> 
    
    <dev class="container">
        <div class="login-form">
            {% if messages %}
                {% for msg in messages %}
                    <p>{{msg}}</p>
                    {% endfor %}
                {% endif %}
         
        <form method="POST" action="{% url 'blog:login' %}">
            {% csrf_token %} 
            {{login_form.as_p}}
            <!-- <input type="text" name="username">
            <input type="password" name="password"> -->
            <input type="submit" value="Log in">  
        </form>
    </dev>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <body>  
{% include 'blog/header.html' %}
    
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% for post in posts %}
                        <div class="post">
                            <div class="date">
                                <p>Опубликовано: {{ post.published_date }}</p>
                            </div>
                            <h1><a href="">{{ post.title }}</a></h1>
                            <p>{{ post.text|linebreaksbr }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </body>
    {% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% load static %}

{%block content %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}"> 
    <dev class="container">
        {% if form.errors %}
        <p>erors form</p>

        {% endif %}
        <div class="register-form">
            {% if messages %}
                {% for msg in messages %}
                    <p>{{msg}}</p>
                    {% endfor %}
                {% endif %}
         
        <form method="POST" action="{% url 'blog:register' %}">
            {% csrf_token %} 
            {{register_form.as_p}}
            <!-- <input type="text" name="username">
            <input type="password" name="password"> -->
            <input type="submit" value="Create account">  
        </form>
    </dev>
</div>
{% endblock %}

blog/templates/index.html
<h1>Hello world</h1>


{% for post in posts %}
    <h1>{{post.title}}</h1>
    <h3>{{post.text}}</h3>
{% endfor %}